name: .NET Core

on: 
  watch:
     types: [ started ] 
  
  pull_request:
    types: [ closed ]
    branches-ignore: [ test ]
    tags-ignore: [ semversion ]
      
jobs:
  build:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read version
      id: package
      uses: juliangruber/read-file-action@v1
      with:
         path: ./appDrive.Connect/appDrive.Connect.csproj
    - name: Echo version
      run: |
         existing_version=$(cat appDrive.Connect/appDrive.Connect.csproj  | grep Version | awk -F\> '{print $2}' | awk -F\< '{print $1}')
         echo $existing_version
         export PREV_VER="$existing_version"
         echo "::set-env name=PREV_VER::$PREV_VER" 
    - name: Read version
      id: versionfragment
      uses: juliangruber/read-file-action@v1
      with:
         path: ./.versionfragment        
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ env.PREV_VER }}
        version-fragment: bug
    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }}
   
    - name: Echo updated version
      run: echo ${{ steps.bump_version.outputs.next-version }}  
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: ${{ env.PREV_VER }}
        replace: ${{ steps.bump_version.outputs.next-version }}
        include: "appDrive.Connect/appDrive.Connect.csproj"
    - name: Commit files
      run: |
        git config --local user.email "tss_jenkins@vytecs.com"
        git config --local user.name "tssjenkins" 
        git branch 
        git add appDrive.Connect/appDrive.Connect.csproj
        git commit -m "update version ${{ steps.bump_version.outputs.next-version }}"
        git branch
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      id: cpr
      with:
        branch: version
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.cpr.outputs.pull-request-number }}
        method: squash
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: v${{ steps.bump_version.outputs.next-version }}
    - name: Bump temp and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: semversion    
    - name: Delete Branch
      run: |
        git config --local user.email "tss_jenkins@vytecs.com"
        git config --local user.name "tssjenkins" 
        git push -d origin version
